#! /bin/sh

if [ "$1" = "bound" ]
then
	ifconfig "$interface" "$ip" broadcast "$broadcast" netmask "$subnet"
	if [ "$router" != "" ]
	then
		route del default
		route add default gw "$router"
	fi
	if [ "$dns" != "" ]
	then
		echo "nameserver $dns" > /etc/resolv.conf
	fi
fi

